services:
    feature_checker.driver:
        class: Lwiesel\FeatureCheckerBundle\Annotations\Driver\FeatureCheckerDriver
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onFilterController }
        arguments:
            - @annotation_reader
            - %feature_checker.features%

    feature_checker.exception_listener:
        class: Lwiesel\FeatureCheckerBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    feature_checker.twig.globals_extension:
        class: Lwiesel\FeatureCheckerBundle\Twig\GlobalsExtension
        arguments:
            - %feature_checker.features%
        tags:
            - { name: twig.extension }
