services:
    feature_checker.driver:
        class: LWI\FeatureCheckerBundle\Annotations\Driver\FeatureCheckerDriver
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onFilterController }
        arguments:
            - @annotation_reader
            - %feature_checker.features%

    feature_checker.exception_listener:
        class: LWI\FeatureCheckerBundle\EventListener\ExceptionListener
        arguments:
            - %feature_checker.disable_undefined%
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    feature_checker.twig.globals_extension:
        class: LWI\FeatureCheckerBundle\Twig\GlobalsExtension
        arguments:
            - %feature_checker.features%
        tags:
            - { name: twig.extension }

    feature_checker.checker:
        class: LWI\FeatureCheckerBundle\Service\FeatureChecker
        arguments:
            - %feature_checker.disable_undefined%
            - %feature_checker.features%
